### ISSUE TITLE
J'arrive plus à bouger

### ISSUE THREAD

**Issue by GoDoco** [jean-voila/sqrt100#26]
quand j'essaye de lancer une scène ou le jeu tout court depuis godot le seul truc que je peux faire c'est regarder autour et tirer alors que tout à l'heure je pouvais bouger

**Comment by jean-voila** [comment]
Sur quelle Map ? `mp01`, `mp02` ? En solo aussi ça te le fait ?

**Comment by GoDoco** [comment]
j'ai testé sur leidenstadt et sur la mp01 je crois (celle qui se lance en mettant jeu solo)

aussi ça m'a affiché masse erreur 
![image](https://github.com/jean-voila/sqrt100/assets/98039119/c1acdbd1-cfd5-4d78-b101-5803ddd6998e)

**Comment by jean-voila** [comment]
S'il y a 7 erreurs c'est normal, un bug qu'on a remarqué avec @Kotto654 mais qui n'affecte pas le bon fonctionnement du jeu. On a prévu de le résoudre demain.

Pour ce qui est des maps, je vais regarder ça, de mon côté je suis sur le commit d'avant @bymedeu .

**Comment by GoDoco** [comment]
ok ok 
je vais faire ce que je peux pour finir la map avant demain mais je devrais retester et réajuster quand on pourra rebouger

**Comment by jean-voila** [comment]
@bymedeu le problème vient de ton push.. même problème que @GoDoco

**Comment by jean-voila** [comment]
> ok ok je vais faire ce que je peux pour finir la map avant demain mais je devrais retester et réajuster quand on pourra rebouger

non, demain on travaille sur le Rapport de Projet, ce n'est pas grave pour la map, je pense qu'il vaut mieux laisser ce qui est déjà fait et qui *fonctionne*, on a déjà du pain sur la planche entre l'administratif et le multijoueur

**Comment by GoDoco** [comment]
ok ok
je testerai si et seulement si il me reste un ptit peu de temps alors ;-;

**Comment by jean-voila** [comment]
t'inquiètes pas, tester ça prend 3 minutes donc oui on aura le temps, mais tester est une chose, repasser pendant des heures sur des défauts futiles qu'on aurait pu résoudre avant (C.F l'erreur que j'ai faite sur le son) en est une autre, la priorité est aux 50 pages de rapport, au texte d'oral, au plan de soutenance, à la *soutenance en Anglais* (R.I.P), au packaging, au site web, et nous sommes à J-6

**Comment by jean-voila** [comment]
e3cfe9eadafdfcfda098ae941e8a1d401b88ecb5
